version: '3'
services:
  postgres.lbg.dev:
    build:
     context: ../../containers/postgres
     args:
      - AMBARI_DDL_URL=${AMBARI_DDL_URL}
    image: hdp/postgres
    networks:
     - dev
    hostname: postgres
    domainname: lbg.dev
  ambari-server.lbg.dev:
    build: 
      context: ../../containers/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: hdp/ambari-server
    networks:
     - dev
    hostname: ambari-server
    domainname: lbg.dev
    ports:
     - "8080:8080"
  master0.lbg.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/master
    privileged: true
    networks:
     - dev
    hostname: master0
    domainname: lbg.dev
    ports:
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     - "50070:50070"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     - "19888:19888"
     # HiveServer2
     - "10000:10000"
     - "9999:9999"
     - "9933:9933"
     - "10015:10015"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     - "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"
     # Kerberos
     - "88"
     # Zookeeper
     - "2181:2181"
  dn0.lbg.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: lbg.dev
    ports:
     # HDFS
     - "50070"
     - "50470"
     - "50075"
     - "50475"
     - "50010"
     - "50020"
     - "50030"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45454"
     - "8042"
     # Solr
     - "8983"
     # Kafka
     - "6667"
     # Zookeeper
     - "2181"
     - "2888"
     - "3888"
  dn1.lbg.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn1
    domainname: lbg.dev
    ports:
     # HDFS
     - "50070"
     - "50470"
     - "50075"
     - "50475"
     - "50010"
     - "50020"
     - "50030"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45454"
     - "8042"
     # Solr
     - "8983"
     # Kafka
     - "6667"
     # Zookeeper
     - "2181"
     - "2888"
     - "3888"
  dn2.lbg.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn2
    domainname: lbg.dev
    ports:
     # HDFS
     - "50070"
     - "50470"
     - "50075"
     - "50475"
     - "50010"
     - "50020"
     - "50030"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45454"
     - "8042"
     # Solr
     - "8983"
     # Kafka
     - "6667"
     # Zookeeper
     - "2181"
     - "2888"
     - "3888"
  kdc.lbg.dev:
    build:
     context: ../../containers/kdc
    image: krb5-server
    networks:
     - dev
    hostname: kdc 
    domainname: lbg.dev
    ports:
     - "88:88"
     - "464:464"
     - "749:749"
    environment:
      KRB5_REALM: LBG.DEV
      KRB5_KDC: kdc.lbg.dev
      KRB5_PASS: 123ABCabc456
    volumes:
     - krb5kdc-data:/var/lib/krb5kdc
networks:
  dev:
    driver: bridge
volumes:
    krb5kdc-data:
